# Generated by Django 2.1.7 on 2019-03-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uclassname', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('uclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.UserClass')),
            ],
        ),
    ]
